### ISSUE TITLE
🐛 UI Bugs

### ISSUE THREAD

**Issue by philsinatra** [EP-Visual-Design/COVID-19-Impact-Project#11]
Having not looked at this in detail for a while, I found some UI issues that should be addressed if you're shopping this around for grants etc.

1. Chart on small screens is basically useless. The chart and labels should be stacked instead of in a row.

![graph](https://user-images.githubusercontent.com/1465808/101054575-065b3680-3557-11eb-94a1-e036ebd35180.png)

---

2. It is unclear exactly what these buttons are doing. The labels need to better indicate what is happening when they're selected. What does _on day:_ do? To me it feels like there should be only one button that says something like "Jump to today".

![date_day-buttons](https://user-images.githubusercontent.com/1465808/101054994-7d90ca80-3557-11eb-88d2-59268053ea1a.png)

---

3. The region buttons should be reorganized into a `select` element with a clear label, e.g. _Sort By_ with options like "Latest Totals", "Since First Death". Additionally, the "- Per 100,000" is confusing. You're offering a lot of data without clear labels for the sorting options, users not familiar with the UI will be confused. Does "- Per 100,000" belong with the first death/latest options or is it a different type of filter?

![button-labels](https://user-images.githubusercontent.com/1465808/101055512-f7c14f00-3557-11eb-9d4c-7a6c8c1a8155.png)

---

4. The function of the "World Wide" button again is not clear. I know that it is resetting the data if you have selected a specific country, but there needs to be a clear label on the button and its position shouldn't be so random. All of the controls of the **Regions** section should be reevaluated for a better UX.

![table-semantics](https://user-images.githubusercontent.com/1465808/101056024-87ff9400-3558-11eb-96c5-cb5456fc952f.png)

---

5. 🐛 When you sort by country, the color indicators do not sort with the rest of the table data.

![color-indicator](https://user-images.githubusercontent.com/1465808/101056142-a8c7e980-3558-11eb-9707-621a0bc02ae3.png)

![country-sort](https://user-images.githubusercontent.com/1465808/101056105-a06fae80-3558-11eb-9e0d-d69597348303.gif)

**Comment by jhtep** [comment]
All good issues.
Thanks for the feedback.
Will add todo tasks
-john-henry
