### ISSUE TITLE
Table Header obsures Sort By: Select drop down

### ISSUE THREAD

**Issue by jhtep** [EP-Visual-Design/COVID-19-Impact-Project#17]
6. Table Header obsures Sort By: Select drop down

![Select drop down](https://user-images.githubusercontent.com/2498297/101187298-2f94c900-3622-11eb-9c8e-4ffa75c9f0a3.png)

**Comment by philsinatra** [comment]
I don't see the select element in the interface. Is this something you're implementing but have not pushed yet?

**Comment by jhtep** [comment]
Fixed in day1 branch
